# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
 - trailing_whitespace
 - force_cast
 - cyclomatic_complexity
 - block_based_kvo
 - type_body_length
 - file_length
 - function_body_length
 - closure_parameter_position
 - function_parameter_count
 - notification_center_detachment

line_length: 130

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
